### ISSUE TITLE
Checklist about Mayfly releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-mayfly#43]
@dev4unet @hippo-an (cc. @MZC-CSC @innodreamer)

안녕하세요.

📅 Mayfly 0.2.x 릴리스 일정이 ~11/25(월)로 예정되어 있습니다. 

현재 릴리스된 서브시스템들의 버전들을 참고하셔서 Mayfly 릴리스를 진행해 주시면 될 것 같습니다. 

릴리스 진행에 필요한 사항이 있으시면 해당 서브시스템 메인테이너께 전달해 주시기 바랍니다. (사전에 협조 요청드린 상태)

Mayfly를 통해 Cloud-Migrator platform 전체를 구동 후 Portal에서 전반적으로 테스트해 볼 계획을 가지고 있습니다. 관련하여 전체 시스템을 구동할 수 있는 추천사양(VM spec)을 README에 포함시켜 주시면 좋을 것 같습니다.

🙋 릴리스 추진과 관련하여 이슈가 있으시면 댓글로 남겨주시기 바랍니다.

☑️ 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
* [x] Mayfly 개발 및 테스트
* [x] Mayfly 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
* [x] Mayfly 실행 지원
* [x] Mayfly 문서화
* [x] Mayfly 릴리스
각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

(참고)
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.

* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by yunkon-kim** [comment]
파악된 서브시스템들의 버전을 공유 드립니다. 참고 바랍니다.
* https://github.com/cloud-barista/cloud-migrator/issues/11#issuecomment-2489974389

**Comment by MZC-CSC** [comment]
CM-Butterfly 에서 테스트 진행한 서브시스템의 버전입니다.

- cloudbaristaorg/cb-spider:0.10.0
- cloudbaristaorg/cb-tumblebug:0.10.0
- cloudbaristaorg/cm-honeybee:0.2.10
- cloudbaristaorg/cm-damselfly:0.2.1
- cloudbaristaorg/cm-beetle:0.2.4
- cloudbaristaorg/cm-cicada:edge (v0.2.3 이후 edge 로 task component 변환 코드의 수정으로 인해 edge 버전을 사용했습니다.)
- cloudbaristaorg/cm-ant:0.2.7

**Comment by MZC-CSC** [comment]
cm-mayfly v0.2.8 릴리스했으며, cm-damselfly:0.2.2 버전이 적용되었으며,
릴리스 문서와 README.md에서 ./mayfly를 ./cm-mayfly로 일부 잘 못 설명된 내용도 수정했습니다.

https://github.com/cloud-barista/cm-mayfly/releases/tag/v0.2.8
cb-spider:0.10.0
cb-tumblebug:0.10.3
cb-mapui:0.10.0
cm-beetle:0.2.5
cm-butterfly-api:0.2.3
cm-butterfly-front:0.2.3
cm-honeybee:0.2.10
cm-damselfly:0.2.2
cm-cicada:0.2.4
cm-grasshopper:0.2.3
cm-ant:0.2.7

**Comment by hippo-an** [comment]
@MZC-CSC @yunkon-kim 
https://github.com/cloud-barista/cloud-migrator/issues/11#issuecomment-2516874143
위 내용과 관련한 수정 사항과 함께 CM-Ant 버전을 0.2.8 로 올렸습니다.

**Comment by yunkon-kim** [comment]
@hippo-an 빠르게 조치해주셔서 감사합니다 :-)

**Comment by yunkon-kim** [comment]
Resolved

**Comment by MZC-CSC** [comment]
아래 버전으로 cm-mayfly v0.3.0 버전 릴리스했습니다.
https://github.com/cloud-barista/cm-mayfly/releases/tag/v0.3.0
cb-spider v0.10.0
cb-tumblebug v0.10.3
cb-mapui v0.10.0
cm-damselfly v0.3.0
cm-honeybee v0.3.0
cm-beetle v0.3.0
cm-grasshopper v:0.3.0
cm-cicada v0.3.0
cm-ant v0.3.0
cm-butterfly v0.3.0
